apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-project
  template:
    metadata:
      labels:
        app: sample-project
    spec:
      containers:
      - name: sample-project
        image: anusha1681990/sampleproject
        ports:
        - containerPort: 3000
